image:
  repository: tccr.io/truecharts/jackett
  pullPolicy: IfNotPresent
  tag: v0.20.781@sha256:96eae64bdf60250418ef7581fa5387c58b2c5963be19582ebc4151ccacc7c488

probes:
  liveness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      tcpSocket:
        port: 3306
      failureThreshold: 5
      initialDelaySeconds: 300
      periodSeconds: 300
      successThreshold: 1
      timeoutSeconds: 300
      
  readiness:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      tcpSocket:
        port: 3306
      failureThreshold: 5
      initialDelaySeconds: 300
      periodSeconds: 300
      successThreshold: 1
      timeoutSeconds: 300
    
  startup:
    enabled: true
    ## Set this to true if you wish to specify your own livenessProbe
    custom: true
    ## The spec field contains the values for the default livenessProbe.
    ## If you selected custom: true, this field holds the definition of the livenessProbe.
    spec:
      tcpSocket:
        port: 3306
      failureThreshold: 5
      initialDelaySeconds: 300
      periodSeconds: 300
      successThreshold: 1
      timeoutSeconds: 300
