
livenessProbe:
  # enabled is a flag to used to enable liveness probe
  enabled: true
  # initialDelaySeconds is a delay before liveness probe is initiated
  initialDelaySeconds: 300
  # periodSeconds decides how often to perform the probe
  periodSeconds: 30
  
readinessProbe:
  # enabled is a flag to used to enable readiness probe
  enabled: true
  # initialDelaySeconds is a delay before readiness probe is initiated
  initialDelaySeconds: 300
  # periodSeconds decides how often to perform the probe
  periodSeconds: 30

startupProbe:
  # enabled is a flag to used to enable readiness probe
  enabled: true
  # initialDelaySeconds is a delay before readiness probe is initiated
  initialDelaySeconds: 300
  # periodSeconds decides how often to perform the probe
  periodSeconds: 30
